title: Documentaci√≥n SIU OPM
description: Guia de usuario para navegar en la plataforma SIU
theme: just-the-docs

url: https://michoacano094.github.io/siu-opm/

permalink: pretty

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  warning:
    title: Warning
    color: red